---
services:
  app:
    image: ghcr.io/fabiogermann/docker-blueiris:master
    ports:
      - 8080:8080
      - 8881:81
    volumes:
      - config:/config:rw
      - data:/data:rw
      - /etc/localtime:/etc/localtime:rw
      - /etc/timezone:/etc/timezone:rw
    #devices:
    #  - "/dev/dri/renderD128:/dev/dri/renderD128"
    environment:
    # DRINODE: /dev/dri/renderD128
      WINEDEBUG: -all
      TZ: "Europe/Berlin"
  ai:
    image: codeproject/ai-server
    ports:
      - 32168:32168
volumes:
  config:
  data:
